<?php

namespace App\Filament\Resources\BranchResource\Pages;

use App\Filament\Forms\UserForm;
use App\Filament\Resources\BranchResource;
use App\Models\Branch;
use App\Models\User;
use Filament\Forms\Components\Section;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Form;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;

class CreateBranch extends CreateRecord
{
    protected static string $resource = BranchResource::class;

    protected function handleRecordCreation(array $data): Model
    {
        $branch = Branch::create([
            'name' => $data['name'],
        ]);

        $user = User::create([
            'branch_id' => $branch->id,
            'username' => $data['username'],
            'email' => $data['email'],
            'firstname' => $data['firstname'],
            'lastname' => $data['lastname'],
            'password' => $data['password'],
            'email_verified_at' => now(),

        ]);

        $user->assignRole('branch_admin');

        return $branch; // TODO: Change the autogenerated stub
    }


    public function form(Form $form): Form
    {
        return $form
            ->schema([
                Section::make()
                    ->schema([
                        TextInput::make('name')
                            ->label('Branch name')
                            ->unique()
                            ->required()
                            ->maxLength(255),
                    ]),
                Section::make('Branch Admin')
                    ->schema(UserForm::schema(true)),
            ]);
    }
}
